### PR TITLE
ENH: Option to configure endpoint, closes #9

### LINKED ISSUE #9: Port dtool-ecs endpoint features into dtool-s3
This needs to be done in a way that is backwards compatible with the existing default authentication methods in dtool-s3 that requires zero setup if aws credentials have been configured using some different tool, e.g. awscli config.

### PR DESCRIPTION
**Pull request by pastewka**
This PR add the option to configure an endpoint (and corresponding access id and secret key) within the dtool config file. This adds the capabilities of the `dtool-ecs` plugin to `dtool-s3`, deprecating `dtool-ecs`.

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @tjelvar-olsson, this PR should address issue #9

**Comment by tjelvar-olsson** [comment]
Hi @pastewka this looks great! Thank you!

I'm on holiday now but when I get back I'll merge, write some tests and make a release. Will probably take two to three weeks. Let me know if you need a release sooner than that.

**Comment by pastewka** [comment]
No worries, thanks a lot

**Comment by tjelvar-olsson** [comment]
@pastewka writing and running tests on my Windows laptop. I've just realised that Windows forces environment variable keys to be upper case. This means that logic to pick up the endpoint, access key id and secret access key fail when set as environment variables (because the bucket name part of it is lower case). I don't think I would have picked this up if I was reading the keys from the dtool config file.

AWS S3 bucket are not allowed to contain uppercase characters (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) so there are no issues with regards to name conflicts based on the use of lower/upper case.

However, if I force the bucket name to be upper case when looking for the setting it would potentially miss settings with buckets named with lower case letters set in the dtool config file.

I'll mull this over for a bit.

Please let me know what your thoughts on this subject are.

@mrmh2 if you have any thoughts on this please let me know too.

**Comment by tjelvar-olsson** [comment]
@pastewka @mrmh2

It turns out that the way os.environ behaves on Windows is a bit crazy.

```
>>> import os
>>> os.environ["crazy"] = "windows"
>>> os.environ
environ({<A LOT CUT OUT>, 'CRAZY': 'windows'})
>>> os.environ["CRAZY"]
'windows'
>>> os.environ["crazy"]
'windows'
>>> os.environ["craZy"]
'windows'
```

However, the behaviour solves the issue for us, so I guess some thought went into implementing this behaviour.

On a side note I must have been doing something else wrong when I discovered this "red herring", as the behaviour means that the code works out of the box.

**Comment by tjelvar-olsson** [comment]
@pastewka  so I have:

- Fixed some flake8 formatting 81caeb5
- Added code to test the new functionality af9371e
- Documented the use of custom endpoints 65b341c
- Created a new release on pypi https://pypi.org/project/dtool-s3/0.12.0/

**Comment by pastewka** [comment]
Hi @tjelvar-olsson - this looks great, thanks for merging this and adding the tests. This should also mean that https://github.com/jic-dtool/dtool-ecs can be deprecated, correct?

**Comment by tjelvar-olsson** [comment]
Yes, I believe that dtool-ecs can be deprecated now. 🙂

**Pull request merged**
